spring:
  datasource:
      username: suneel
      password: welcome
      url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 9090
     
   

