spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: suneel
    password: welcome
    url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    hibernate:
      ddl-auto: validate 
      show-sql: true 
  management:
    endpoints:
      web:
        exposure:
          include: '*'
server:
  port: 9090
# Application Messages Goes Here
auth-service:
  messages:
    userReg: User Created
    userRegErr: User Creation Failed
    login: Login Success
    loginErr: Invalid Credentials 
