spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: suneel
    password: welcome
    url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    hibernate:
      ddl-auto: validate 
      show-sql: true 
  management:
    endpoints:
      web:
        exposure:
          include: '*'
server:
  port: 9093
# Application Messages Goes Here
product-service:
  messages:
    addOrders: Orders Added Successfully
    addOrdersErr: Failed to add orders
    updateOrder: Order Updated Successfully
    updateOrderErr: Failed to update order
    selectOrdersByUserId: Orders Retrieved Successfully
    selectOrdersByUserIdErr: Failed to fetch all orders
    selectOrdersByDateAndStatus: Orders Retrieved Successfully
    selectOrdersByDateAndStatusErr: Failed to retrieve the orders
    fetchOrders: All Orders Retrieved Successfully
    fetchOrdersErr: Failed to fetch all orders
  
