
server:
  port: 9091
# Application Messages Goes Here
product-service:
  messages:
    categoryAdded: Category Added Successfully
    categoryAddErr: Failed to add category
    categoryUpdate: Category Updated Successfully
    categoryUpdateErr: Failed to update category
    categoryFetch: All categorys fetched successfully
    categoryFetchErr: Failed to fetch all categories
    categorySelect: Category Retrieved Successfully
    categorySelectErr: Failed to retrieve category
    categoryDeleted: Category Deleted Successfully
    categoryDeletedErr: Failed to delete category
    productAdded: Product Added Successfully
    productAddedErr: Failed to add product
    productUpdate: Product Updated Successfully
    productUpdateErr: Failed to update category
    productFetch: All Products fetched successfully
    productFetchErr: Failed to fetch all products
    productSelect: Product Retrieved Successfully
    productSelectErr: Failed to retrieve product
    productDeleted: Product Deleted Successfully
    productDeletedErr: Failed to delete product
